# Generated by Django 2.1 on 2019-03-21 01:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mao_era.models.blocks
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.core.models
import wagtail.images.blocks
import wagtail.images.models
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_start', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid date (YYYY, YYYY-MM, or YYYY-MM-DD)', regex='^(-)?\\d{4}(-[01][0-9](-[0-3][0-9])?)?$')])),
                ('date_end', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid date (YYYY, YYYY-MM, or YYYY-MM-DD)', regex='^(-)?\\d{4}(-[01][0-9](-[0-3][0-9])?)?$')])),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ImageResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('file', models.ImageField(height_field='height', upload_to=wagtail.images.models.get_upload_to, verbose_name='file', width_field='width')),
                ('width', models.IntegerField(editable=False, verbose_name='width')),
                ('height', models.IntegerField(editable=False, verbose_name='height')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('focal_point_x', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_y', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_width', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(editable=False, null=True)),
                ('file_hash', models.CharField(blank=True, editable=False, max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(blank=True, max_length=20)),
                ('creator', models.TextField(blank=True)),
                ('publisher', models.TextField(blank=True)),
                ('rights', models.TextField(blank=True)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('collection', models.ForeignKey(default=wagtail.core.models.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Collection', verbose_name='collection')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='ImageResourceRendition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_spec', models.CharField(db_index=True, max_length=255)),
                ('file', models.ImageField(height_field='height', upload_to=wagtail.images.models.get_rendition_upload_to, width_field='width')),
                ('width', models.IntegerField(editable=False)),
                ('height', models.IntegerField(editable=False)),
                ('focal_point_key', models.CharField(blank=True, default='', editable=False, max_length=16)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='mao_era.ImageResource')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectBiographyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectBiographyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('byline', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('biography', wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('content', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('image_align', mao_era.models.blocks.AlignmentChoiceBlock())]))]))]))])),
                ('footnotes', wagtail.core.fields.StreamField([('footnote', wagtail.core.blocks.StructBlock([('number', wagtail.core.blocks.IntegerBlock(min_value=1)), ('footnote', wagtail.core.blocks.TextBlock())]))], blank=True)),
                ('further_reading', wagtail.core.fields.RichTextField(blank=True)),
                ('featured_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='featured_biographies', to='mao_era.ImageResource')),
                ('related_objects', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='_objectbiographypage_related_objects_+', to='mao_era.ObjectBiographyPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ObjectBiographyPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='mao_era.ObjectBiographyPage')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectBiographySource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='mao_era.ObjectBiographyPage')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectBiographyTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='mao_era.ObjectBiographyPage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mao_era_objectbiographytag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PDFResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(blank=True, max_length=20)),
                ('creator', models.TextField(blank=True)),
                ('publisher', models.TextField(blank=True)),
                ('rights', models.TextField(blank=True)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('text_file', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=100)),
                ('description', wagtail.core.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SourcePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('source_type', models.CharField(choices=[('audio', 'Audio'), ('image', 'Image'), ('pdf', 'PDF'), ('text', 'Text'), ('video', 'Video')], max_length=5)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TextResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(blank=True, max_length=20)),
                ('creator', models.TextField(blank=True)),
                ('publisher', models.TextField(blank=True)),
                ('rights', models.TextField(blank=True)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('text', wagtail.core.fields.RichTextField()),
                ('source', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='mao_era.SourcePage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimelinePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='URLResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(blank=True, max_length=20)),
                ('creator', models.TextField(blank=True)),
                ('publisher', models.TextField(blank=True)),
                ('rights', models.TextField(blank=True)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('source_url', models.URLField(blank=True, verbose_name='URL')),
                ('source', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='mao_era.SourcePage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pdfresource',
            name='source',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='mao_era.SourcePage'),
        ),
        migrations.AddField(
            model_name='objectbiographysource',
            name='source',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='biographies', to='mao_era.SourcePage'),
        ),
        migrations.AddField(
            model_name='objectbiographyplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biographies', to='mao_era.Place'),
        ),
        migrations.AddField(
            model_name='objectbiographypage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='mao_era.ObjectBiographyTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='objectbiographyevent',
            name='biography',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mao_era.ObjectBiographyPage'),
        ),
        migrations.AddField(
            model_name='objectbiographyevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biographies', to='mao_era.Event'),
        ),
        migrations.AddField(
            model_name='imageresource',
            name='source',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mao_era.SourcePage'),
        ),
        migrations.AddField(
            model_name='imageresource',
            name='uploaded_by_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by user'),
        ),
        migrations.AlterUniqueTogether(
            name='objectbiographysource',
            unique_together={('biography', 'source')},
        ),
        migrations.AlterUniqueTogether(
            name='objectbiographyplace',
            unique_together={('biography', 'place')},
        ),
        migrations.AlterUniqueTogether(
            name='objectbiographyevent',
            unique_together={('biography', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='imageresourcerendition',
            unique_together={('image', 'filter_spec', 'focal_point_key')},
        ),
    ]
