# Generated by Django 2.1 on 2019-03-14 12:33

from django.db import migrations, models
import django.db.models.deletion
import mao_era.models.blocks
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('mao_era', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectBiographyPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sourcepageimage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='sourcepageimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sourcepageimage',
            name='source',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='note',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.RemoveField(
            model_name='objectbiographypage',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='objectbiographypage',
            name='date_start',
        ),
        migrations.AddField(
            model_name='objectbiographypage',
            name='footnotes',
            field=wagtail.core.fields.StreamField([('footnote', wagtail.core.blocks.StructBlock([('number', wagtail.core.blocks.IntegerBlock(min_value=1)), ('footnote', wagtail.core.blocks.TextBlock())]))], blank=True),
        ),
        migrations.AddField(
            model_name='objectbiographypage',
            name='further_reading',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='sourceimage',
            name='source',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mao_era.SourcePage'),
        ),
        migrations.AlterField(
            model_name='objectbiographypage',
            name='biography',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('content', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('image_align', mao_era.models.blocks.AlignmentChoiceBlock())]))]))]))]),
        ),
        migrations.AlterField(
            model_name='objectbiographypage',
            name='featured_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='featured_biographies', to='mao_era.SourceImage'),
        ),
        migrations.AlterField(
            model_name='objectbiographypage',
            name='related_objects',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='_objectbiographypage_related_objects_+', to='mao_era.ObjectBiographyPage'),
        ),
        migrations.AlterField(
            model_name='sourceimage',
            name='caption',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sourcepage',
            name='source_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('image', 'Image'), ('pdf', 'PDF'), ('text', 'Text'), ('video', 'Video')], max_length=5),
        ),
        migrations.DeleteModel(
            name='SourcePageImage',
        ),
        migrations.AddField(
            model_name='objectbiographyplace',
            name='biography',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='mao_era.ObjectBiographyPage'),
        ),
        migrations.AddField(
            model_name='objectbiographyplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biographies', to='mao_era.Place'),
        ),
        migrations.AlterUniqueTogether(
            name='objectbiographyplace',
            unique_together={('biography', 'place')},
        ),
    ]
