# Generated by Django 2.1 on 2019-03-15 09:52

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mao_era', '0002_auto_20190314_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcePDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('text_file', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SourceText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('text', wagtail.core.fields.RichTextField()),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SourceURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('source_url', models.URLField(blank=True, verbose_name='URL')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.RemoveField(
            model_name='sourceimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='sourcepage',
            name='copyright_statement',
        ),
        migrations.RemoveField(
            model_name='sourcepage',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='sourcepage',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='sourcepage',
            name='text',
        ),
        migrations.RemoveField(
            model_name='sourcepage',
            name='text_file',
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourcepage',
            name='creator',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourcepage',
            name='date',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourcepage',
            name='publisher',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourcepage',
            name='rights',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sourceurl',
            name='source',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='mao_era.SourcePage'),
        ),
        migrations.AddField(
            model_name='sourcetext',
            name='source',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='mao_era.SourcePage'),
        ),
        migrations.AddField(
            model_name='sourcepdf',
            name='source',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='mao_era.SourcePage'),
        ),
    ]
