# Generated by Django 2.1 on 2019-05-05 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mao_era', '0004_auto_20190430_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectbiographypage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='featured_biographies', to='wagtailimages.Image'),
        ),
    ]
