# Generated by Django 2.1 on 2019-05-07 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('mao_era', '0005_auto_20190505_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfresource',
            name='text_file',
        ),
        migrations.AddField(
            model_name='pdfresource',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='wagtaildocs.Document'),
            preserve_default=False,
        ),
    ]
