# Generated by Django 2.1 on 2019-11-07 10:56

from django.db import migrations
import mao_era.models.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('mao_era', '0019_auto_20191029_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectbiographypage',
            name='biography',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('content', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'superscript', 'ol', 'ul', 'link', 'document-link', 'image', 'embed', 'anchor', 'anchorid', 'blockquote'])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('image_align', mao_era.models.blocks.AlignmentChoiceBlock())]))]))]))]),
        ),
    ]
