services:
  django:
    build:
      context: ..
      dockerfile: ./services/django/Dockerfile
    restart: unless-stopped
    ports:
      - ${DJANGO_PORT:-8000}
      # - "8000:8000"
    volumes:
      - ../volumes/django:/app
    env_file:
      - ../compose/.env
    environment:
      VIRTUAL_HOST: "${DJANGO_VIRTUAL_HOST:-${VIRTUAL_HOST:-localhost,127.0.0.1}}"
      VIRTUAL_PATH: "${DJANGO_VIRTUAL_PATH:?Django virtual path not set}"
      VIRTUAL_PROTO: "${DJANGO_VIRTUAL_PROTO:-${VIRTUAL_PROTO:-http}}"
      VIRTUAL_PORT: ${DJANGO_PORT:-8000}
    command:
      [
        "/usr/local/bin/gunicorn",
        "mao.wsgi",
        "--bind",
        "0.0.0.0:8000",
        "--chdir=/app",
        "--timeout",
        "180",
        "--forwarded-allow-ips='*'",
      ]
    depends_on:
      postgres:
        condition: service_healthy
      # elasticsearch:
        # condition: service_healthy
