# Generated by Django 2.1 on 2019-04-02 08:11

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mao_era', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='body',
            field=wagtail.core.fields.RichTextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objectbiographypage',
            name='footnotes',
            field=wagtail.core.fields.StreamField([('footnote', wagtail.core.blocks.StructBlock([('number', wagtail.core.blocks.IntegerBlock(min_value=1)), ('footnote', wagtail.core.blocks.TextBlock())]))], blank=True, null=True),
        ),
    ]
