# Generated by Django 2.1 on 2019-04-30 08:41

from django.db import migrations, models
import django.db.models.deletion
import mao_era.models.blocks
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('mao_era', '0003_auto_20190402_0911'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imageresourcerendition',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='imageresourcerendition',
            name='image',
        ),
        migrations.RemoveField(
            model_name='imageresource',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='imageresource',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='imageresource',
            name='file',
        ),
        migrations.RemoveField(
            model_name='imageresource',
            name='file_hash',
        ),
        migrations.RemoveField(
            model_name='imageresource',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='imageresource',
            name='focal_point_height',
        ),
        migrations.RemoveField(
            model_name='imageresource',
            name='focal_point_width',
        ),
        migrations.RemoveField(
            model_name='imageresource',
            name='focal_point_x',
        ),
        migrations.RemoveField(
            model_name='imageresource',
            name='focal_point_y',
        ),
        migrations.RemoveField(
            model_name='imageresource',
            name='height',
        ),
        migrations.RemoveField(
            model_name='imageresource',
            name='uploaded_by_user',
        ),
        migrations.RemoveField(
            model_name='imageresource',
            name='width',
        ),
        migrations.AddField(
            model_name='imageresource',
            name='image',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='wagtailimages.Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageresource',
            name='source',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mao_era.SourcePage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objectbiographypage',
            name='biography',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('content', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'superscript', 'ol', 'ul', 'link', 'document-link', 'image', 'embed', 'anchor', 'blockquote'])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('image_align', mao_era.models.blocks.AlignmentChoiceBlock())]))]))]))]),
        ),
        migrations.DeleteModel(
            name='ImageResourceRendition',
        ),
    ]
