# Generated by Django 2.1 on 2019-05-09 19:48

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mao_era', '0006_auto_20190507_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcepage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Description of whole source'),
        ),
    ]
