# Generated by Django 2.1 on 2019-05-09 20:42

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mao_era', '0007_sourcepage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectbiographypage',
            name='footnotes',
            field=wagtail.core.fields.StreamField([('footnote', wagtail.core.blocks.StructBlock([('number', wagtail.core.blocks.IntegerBlock(min_value=1)), ('footnote', wagtail.core.blocks.TextBlock())]))], blank=True, default=''),
            preserve_default=False,
        ),
    ]
