# Generated by Django 2.1 on 2019-05-16 03:14

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mao_era', '0008_auto_20190509_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectbiographypage',
            name='footnotes',
            field=wagtail.core.fields.StreamField([('footnote', wagtail.core.blocks.StructBlock([('number', wagtail.core.blocks.IntegerBlock(min_value=1)), ('footnote', wagtail.core.blocks.RichTextBlock())]))], blank=True),
        ),
    ]
