# Generated by Django 2.1 on 2019-05-29 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mao_era', '0010_pdfresource_preview_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageresource',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='pdfresource',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='textresource',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='urlresource',
            options={'ordering': ['sort_order']},
        ),
    ]
