# Generated by Django 2.1 on 2019-06-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mao_era', '0014_auto_20190619_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageresource',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pdfresource',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='textresource',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='urlresource',
            name='title',
            field=models.TextField(),
        ),
    ]
