# Generated by Django 2.1 on 2019-10-29 10:40

from django.db import migrations, models
import django.db.models.deletion
import mao_era.models.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('mao_era', '0016_auto_20190714_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('content', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'superscript', 'ol', 'ul', 'link', 'document-link', 'image', 'embed', 'anchor', 'blockquote'])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('image_align', mao_era.models.blocks.AlignmentChoiceBlock())]))]))]))])),
                ('footnotes', wagtail.core.fields.StreamField([('footnote', wagtail.core.blocks.StructBlock([('number', wagtail.core.blocks.IntegerBlock(min_value=1)), ('footnote', wagtail.core.blocks.RichTextBlock())]))], blank=True)),
                ('further_reading', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
