# Generated by Django 2.1 on 2019-10-29 13:58

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mao_era', '0017_essaypage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essaypage',
            old_name='body',
            new_name='biography',
        ),
        migrations.RemoveField(
            model_name='essaypage',
            name='further_reading',
        ),
        migrations.AddField(
            model_name='essaypage',
            name='byline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='essaypage',
            name='related_objects',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='_essaypage_related_objects_+', to='mao_era.EssayPage'),
        ),
    ]
