# Generated by Django 2.1 on 2019-10-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('mao_era', '0018_auto_20191029_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essaypage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='essaypage',
            name='related_objects',
        ),
        migrations.AlterField(
            model_name='objectbiographypage',
            name='byline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='objectbiographypage',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='EssayPage',
        ),
    ]
